### ISSUE TITLE
Forum (READ ON!)

### ISSUE THREAD

**Issue by Besleh** [Murdy007/Wizzy#11]
If william likes it / accepts it i made a forum to easier have all stuff on one place

http://wizzy.enjin.com/forum

not official yet (til william accepts it)  if he do il pass the ownership to him

**Comment by Murdy007** [comment]
Jeez you must be a fan - I will accept the forum. Contact me at william.evans7@xtra.co.nz 
I am currently working on a new update to fix as many issues as possible.
Please reply asap and save my email so I can delete this post so my email is not public.

**Comment by Besleh** [comment]
saved
