### ISSUE TITLE
Pack code for the pack?

### ISSUE THREAD

**Issue by KamranMackey** [Murdy007/Wizzy#3]
Hi, I can't find the pack code for Wizzy anywhere! :cry:

**Comment by Murdy007** [comment]
Hi,
I am sorry for you to have this problem and not being able to download Wizzy. I thought that the atlauncher posted the code on the website. The description has been updated and the code is wizzymc. I would like to give you my full apology on the matter and I hope that you can download and enjoy Wizzy from now on. In a few days there will be a proper mode selection which is not currently available but is in the works, at the moment I suggest either selecting your own selection or using select recommended. Note that only one or two mods from select recommend may be removed in the mainline but everything should be fine at the moment.
Kind regards,
Murdy007

**Comment by Murdy007** [comment]
Remember to contact us again if any new issues appear!

**Comment by Murdy007** [comment]
Also remember that with semi public packs, once you enter the code and add the pack, it may say that the pack is already installed. But once you scroll down to access the pack, it may not be there, if this happens, restart the launcher. 
Thanks,
Murdy007

**Comment by KamranMackey** [comment]
Thank you so much @Murdy007. I really appreciate it! :smile:
