### ISSUE TITLE
OpenGL console spam

### ISSUE THREAD

**Issue by supercrasher** [Murdy007/Wizzy#5]
Whenever I start the pack,no matter the mods I have installed. my console spams this after minecraft finished loading(btw the loading screen doesn't show up,instead there is a white screen):
[29/4/2016 13:31:34 PM] [Client thread/ERROR]: ########## GL ERROR ##########
[29/4/2016 13:31:34 PM] [Client thread/ERROR]: @ Pre render
[29/4/2016 13:31:34 PM] [Client thread/ERROR]: 1282: Invalid operation

**Comment by Murdy007** [comment]
Thank You for bringing this to my attention. Can you please tell me if you have modular powersuits installed, and do you have 64-bit or 32-bit Java? If you do not have 64-bit java, please change to it.

**Comment by supercrasher** [comment]
I don't have modular powersuits installed and I have the 64 bit java version

**Comment by Murdy007** [comment]
In the AtLauncher, under settings, then Java/Minecraft, can you tell me the values of Initial Memory/Ram, Maximum Memory/RAM and the PermGen Size.

    On Saturday, 30 April 2016 11:37 AM, supercrasher <notifications@github..com> wrote:
 

 I don't have modular powersuits installed and I have the 64 bit java version—

**Comment by supercrasher** [comment]
I decided to delete and reinstall the instance today and it worked,the pack works now. I did this same thing over and over yesterday through reinstalling or deleting the pack and installing again,and even gone so far that I reinstalled the launcher.This time though I didn't put in fastcraft so that might be the cause but I kinda doubt that because yesterday i've tried playing without any of the optional mods and it still didn't work.
Also,I attached this photo with the information you asked
![capture](https://cloud.githubusercontent.com/assets/6376948/14934835/776a267c-0ec6-11e6-81a1-f2647e61d7c7.PNG)

**Comment by Murdy007** [comment]
It is great that it works now. From the screenshot it shows all the memory info is fine. If it works now without fastcraft I will put that down as the cause and reconsider it in the pack and report the issue to the mod maker. Thank You for playing Wizzy and have a nice day!
