### ISSUE TITLE
Crash tesseract

### ISSUE THREAD

**Issue by Besleh** [Murdy007/Wizzy#8]
made a tesseract and r clicked it and game crashed

http://pastebin.com/076Sw6AQ

**Comment by Murdy007** [comment]
Yes that is happening to me too. I am looking into a fix for this issue as fast as I can as this is a big problem. Thankyou for the report.
William

**Comment by Besleh** [comment]
i been looking around in forumss of ways to fix it but not sure what one is the best

**Comment by Besleh** [comment]
might have spotted the tessseract problem  might be wrong but 

frequenzy is -1  and i think it neds to be 0 or +1 or more (im not sure) but this is the only iregular thing i spotted

**Comment by Murdy007** [comment]
I have seen that this is fixed by updating thermal expansion. Will be fixed in next Wizzy release.
