### ISSUE TITLE
(not issue) few  changes just a sugestion =) to make it less buggy

### ISSUE THREAD

**Issue by Besleh** [Murdy007/Wizzy#9]
first i think tis modpack needs a forum =) (i can help)

Added mods
Aroma Core
Aroma Backup   (saving every 10 mins since well its a dangerous world lol)
(architecture craft) removed it again it had conflicting recepie) (toomanyrecepies might fix it)
(Scematica) removed again since it was buggy) 

Config changes : 
MCA: 
 # True if regular Minecraft mobs can attack villagers. False to prevent mobs from attacking any villager.
    B:"Allow mob attacks"=false (mobs kept killing my villagers lol)
 # Toggles giving the crystal ball to new players on join. WARNING: If this is false, you must spawn the crystal ball in later manually!
    B:"Give crystal ball"=false   (i got one everytime i logged in since i dint use it or it bugged)

PROPS
    #  [default: false]
    B:clayDrops=True   (Taks forever to make them) with all the dye etc

**Comment by Besleh** [comment]
you can make power banks with transmute table btw lol

**Comment by Murdy007** [comment]
thanks i'm just going on holiday for a week but will be back soon to work on Wizzy!

**Comment by Besleh** [comment]
want me to make a forrum in the meanwile?

**Comment by Murdy007** [comment]
Just replied to your post about the forum. Email me. I will look into adding the aroma mods and I will look into architecture craft. I will also add those config changes to the next version. Thankyou very much for your help with the modpack, it is much appreciated.
